const INCREMENTO = 'INCREMENTO';
const DECREMENTO = 'DECREMENTO';
const IMPAR = 'IMPAR';
const INCREMENTO_ASYNC = "INCREMENTO_ASYNC"
module.exports = {
  INCREMENTO,
  DECREMENTO,
  IMPAR,
  INCREMENTO_ASYNC
}